################################################################################
# Generated using Joshua T. Fisher's 'CMake Builder'.
# Link: https://github.com/playmer/CmakeBuilder 
################################################################################
target_sources(Physics2d
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Physics2dStandard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Physics2dStandard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/PhysicsSpace2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/PhysicsSpace2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/RigidBody2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/RigidBody2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/Colliders/Collider2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/Colliders/Collider2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/Colliders/Collider2dPair.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/Colliders/Collider2dPair.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/Colliders/BoxCollider2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/Colliders/BoxCollider2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/Colliders/CircleCollider2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/Colliders/CircleCollider2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/CollisionDebug.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/CollisionDebug.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/Physics2dDebugDrawConfig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/Physics2dDebugDrawConfig.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CollisionDetection/CollisionLibrary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CollisionDetection/CollisionLibrary.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CollisionDetection/ContactManifold2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CollisionDetection/ContactManifold2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Constraints/ConstraintSolver.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Constraints/ConstraintSolver.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Constraints/Constraint.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Constraints/Constraint.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Constraints/ContactConstraint.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Constraints/ContactConstraint.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Constraints/ConstraintUtilities.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Constraints/ConstraintUtilities.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Resources/Physics2dMaterial.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Resources/Physics2dMaterial.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ZeroUtilities.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ZeroUtilities.hpp
)
